config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'listings#index'
  resources :listings
  get 'listings/:id/purchase', to: 'listings#purchase', as: 'purchase_listing'
  get 'orders', to: 'orders#index', as: 'orders'
  get 'orders/:id', to: 'orders#show', as: 'order'
  post 'orders/new', to: 'orders#create', as: 'new_order'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
    has_one_attached :image
    belongs_to :user, dependent: :destroy
    has_one :order

    validates :name, :description, :functional_condition, :cosmetic_condition ,:image, presence: true
    validates :price, :cosmetic_condition, :functional_condition, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
    validates :cosmetic_condition, :functional_condition, numericality: {less_than_or_equal_to: 3 }
    
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :listing

  validates :listing_id, uniqueness:  true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :listings
  has_many :orders

  validates :suburb, :state, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:suburb, :state])
    devise_parameter_sanitizer.permit(:account_update, keys: [:suburb, :state])
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[ show edit update destroy purchase ]
  before_action :authenticate_user!, only: %i[ new edit update destroy purchase ]
  before_action :authorise_action, only: %i[ edit update destroy ] 

  # GET /listings or /listings.json
  def index
    # loads all listings
    @listings = Listing.all
  end

  # GET /listings/1 or /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings or /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1 or /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1 or /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # GET /listings/1/purchase
  def purchase
  end  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      # loads the listing identified by param id
      @listing = Listing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:name, :price, :category, :console_compatibility, :functional_condition, :cosmetic_condition, :description, :user_id, :image)
    end

    # Only allows the action on a listing if the current user is the listing's creator
    def authorise_action
      unless @listing.user == current_user
        redirect_to listings_path, alert: "You do not have permission to perform this action."
      end
    end
    
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    before_action :order_params
    before_action :find_order, only: %i[ show ]
    before_action :authenticate_user!
    
    # get /orders
    def index
        #loads all orders as well as associated users and listings
        @orders = Order.all.eager_load(:user, :listing)
    end

    # get /orders/:id
    def show
    end

    # POST /orders
    def create
        @order = Order.new(user_id: params[:user_id], listing_id: params[:listing_id])

        if @order.save
            redirect_to @order, notice: "Order was successfully created."
        else
            redirect_to :root, notice: "Error, this item could not be purchased."
        end
    end

    private
        # Not required for order, but rails requires presence
        def order_params 
        end
        
        # find the order object based on id param
        def find_order
            # loads the order identified by the param id, as well as that
            # order's associated user, and listing
            @order = Order.eager_load(:user, :listing).find(params[:id])
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Game Away</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <span>
        <p class="alert"><%= alert %></p>
        <%= yield %>
      </span>
    </div>
  </body>
</html>

app/views/listings/_card.html.erb
<div class="card" style="width: 18rem;">
  <%= image_tag listing.image, class: 'card-img' if listing.image.attached? %>
  <div class="card-body">
    <h5 class="card-title"> <%= listing.name %> </h5>
    <p class="card-text"> $<%= listing.price %> </p>
    <p class="card-text"> Functional Condition: <%= listing.functional_condition %> / 3 </p>
    </span>
    <p class="card-text"> Cosmetic Condition: <%= listing.cosmetic_condition %> / 3</p>
    <p>Item Location: <%= listing.user.suburb %>, <%= listing.user.state%></p>

    <a href='<%= listing_path(listing) %>' class="btn btn-primary">View</a>
    <% if user_signed_in? %>
      <% if listing.user.id == current_user.id %>
        <a href='<%= edit_listing_path(listing) %>' class="btn btn-primary">Edit</a>
        <%= link_to 'Delete', listing_path(listing), method: :delete, class: 'btn btn-danger', :data => {:confirm => 'Are you sure?'} %>
      <% else %>
        <%= link_to 'Purchase', purchase_listing_path(listing), class: 'btn btn-success' %>
      <% end %>
    <% else %>
      <%= link_to 'Purchase', purchase_listing_path(listing), class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/listings/_form.html.erb
<br>
<%= form_with(model: listing, local: true) do |form| %>
  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control', placeholder: 'Name' %>
  </div>
  
  <div class="field form-group">
    <%= form.label :price %>
    <%= form.number_field :price, class: 'form-control', placeholder: 'Price' %>
    <small id="priceHelp" class="form-text text-muted">Enter whole numbers only.</small>
  </div>

  <div class="field form-group">
    <%= form.label :category %>
    <%= form.select :category, options_for_select(['Consoles', 'Games', 'Controllers', 'Bundles' ,'Miscellaneous']), 
    {include_blank: true}, {class: "form-control form-select"} %>
  </div>
  
  <div class="field form-group">
    <%= form.label :console_compatibility %>
    <% console_options = [['Sony',['Playstation 5', 'Playstation 4', 'Playstation 3', 'Playstation 2', 'Playstation']], 
    ['Microsoft', ['Xbox Series X', 'Xbox Series S', 'Xbox One', 'Xbox 360', 'Xbox'] ],
    ['Nintendo', ['Switch', 'Wii U', 'Wii', 'GameCube', '64'] ],
    ['Other', ['PC', 'Other'] ] ] %>
    <%= form.select :console_compatibility, grouped_options_for_select(console_options, nil), 
    {include_blank: true}, {class: "form-control form-select"} %>
  </div>
  
  <div class="field form-group">
    <%= form.label :functional_condition %>
    <%= form.select :functional_condition, options_for_select([ 
      ['1: Not functional; for parts or repair', 1], 
      ['2: Works the majority of the time with some malfunctions/bugs/errors', 2], 
      ['3: Works flawlessly', 3] ]), 
    {include_blank: true}, {class: "form-control form-select"} %>
  </div>

  <div class="field form-group">
    <%= form.label :cosmetic_condition %>
    <%= form.select :cosmetic_condition, options_for_select([ 
      ['1: Heavy damage / scratching', 1], 
      ['2: Some visible damage / scratching', 2], 
      ['3: No scratches or damage', 3] ]), 
    {include_blank: true}, {class: "form-control form-select"} %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id%>
  </div>

  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control', placeholder:'Description' %>
  </div>

  <div class="field form-group">
    <%= form.label :image %>
    <%= form.file_field :image, accept: 'image/jpg, image/jpeg, image/png', class: 'form-control'%>
  </div>

  <br>

  <div class="actions">
    <%= form.submit 'Create Listing', class: 'btn btn-success' %>
  </div>

<% end %>

app/views/listings/_table.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Category</th>
      <th>Console compatibility</th>
      <th>Functional condition</th>
      <th>Cosmetic condition</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.name %></td>
        <td><%= listing.price %></td>
        <td><%= listing.category %></td>
        <td><%= listing.console_compatibility %></td>
        <td><%= listing.functional_condition %></td>
        <td><%= listing.cosmetic_condition %></td>
        <td><%= listing.description %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1>
<br>
<div class="row">
  <% @listings.each do |listing| %>
    <% if listing.order == nil %>
      <%= render 'card', listing: listing, class: 'col-3' %>
    <% end %>
  <% end %>
</div>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>
<br>
<%= link_to 'Back', listings_path, class:'btn btn-primary' %>

app/views/listings/purchase.html.erb
<p id="notice"><%= notice %></p>

<h1>
  Checkout
</h1>

<h3>
  <br><%= @listing.name %>
</h3>

<%= image_tag @listing.image %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Category</th>
      <th scope="col">Console Compatibility</th>
      <th scope="col">Functional Condition</th>
      <th scope="col">Cosmetic Condition</th>
      <th scope="col">Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @listing.category %></td>
      <td><%= @listing.console_compatibility %></td>
      <td><%= @listing.functional_condition %> / 3</td>
      <td><%= @listing.cosmetic_condition %> / 3</td>
      <td><%= @listing.description %></td>
    </tr>
  </tbody>
</table>

<h3><br>Total: $<%= @listing.price %></h3>
<%= link_to 'Cancel', listing_path(@listing), class: 'btn btn-danger' %>
<!-- order's user_id is the buyer -->
<%= link_to 'Confirm Purchase', new_order_path(user_id: current_user.id, listing_id: @listing.id), class: 'btn btn-success', method: :post %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @listing.name %>
</h1>

<%= image_tag @listing.image %>

<p>
  <strong>Price:</strong>
  $<%= @listing.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= @listing.category %>
</p>

<p>
  <strong>Console compatibility:</strong>
  <%= @listing.console_compatibility %>
</p>

<p>
  <strong>Functional condition:</strong>
  <%= @listing.functional_condition %> / 3 :
  <% if @listing.functional_condition == 1 %>
  <%= 'Not functional; for parts or repair' %>
  <% elsif @listing.functional_condition == 2 %>
  <%= 'Works the majority of the time with some bugs/errors' %>
  <% elsif @listing.functional_condition == 3 %>
  <%= 'Works flawlessly'%>
  <% end %>
</p>

<p>
  <strong>Cosmetic condition:</strong>
  <%= @listing.cosmetic_condition %> / 3 :
  <% if @listing.cosmetic_condition == 1 %>
  <%= 'Heavy damage / scratching' %>
  <% elsif @listing.cosmetic_condition == 2 %>
  <%= 'Some visible damage / scratching' %>
  <% elsif @listing.cosmetic_condition == 3 %>
  <%= 'No scratches or damage'%>
  <% end %>

</p>

<p>
    <strong>Item Location: </strong>
    <%= @listing.user.suburb %>,
    <%= @listing.user.state%>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<%= link_to 'Back', listings_path, class: 'btn btn-primary' %>
<% if user_signed_in? && @listing.user == current_user %>
  <%= link_to 'Edit', edit_listing_path(@listing), class: 'btn btn-warning' %>
  <%= link_to 'Delete', listing_path(@listing), method: :delete, class: 'btn btn-danger', :data => {:confirm => 'Are you sure?'} %>
<% else %>
  <%= link_to 'Purchase', purchase_listing_path(@listing), class: 'btn btn-success' %>
<% end %>

app/views/orders/_card.html.erb
<div class="card" style="width: 18rem;">
  <%= image_tag listing.image, class: 'card-img' if listing.image.attached? %>
  <div class="card-body">
    <h5 class="card-title"> <%= listing.name %> </h5>
    <p class="card-text"> $<%= listing.price %> </p>
    <p class="card-text"> Functional Condition: <%= listing.functional_condition %> / 3 </p>
    </span>
    <p class="card-text"> Cosmetic Condition: <%= listing.cosmetic_condition %> / 3</p>
    <p>Item Location: <%= listing.user.suburb %>, <%= listing.user.state%></p>
    <a href='<%= order_path(listing.order) %>' class="btn btn-primary">View</a>
  </div>
</div>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Orders</h1>
<br>
<div class="row">
  <% @orders.each do |order| %>
    <% if order.user == current_user %>
        <%= render 'card', listing: order.listing, class: 'col-3' %>
    <% end %>
  <% end %>
</div>

app/views/orders/show.html.erb
<h1><%= @order.listing.name%></h1>
<br>

<h2 id='purchase_message'>Successful Purchase!</h2>
<p>
Purchased at: 
<%= @order.created_at %>
</p>

<%= image_tag @order.listing.image %>

<br>
<br>

<p> <strong>Seller: </strong><%= @order.listing.user.email%></p>
<p> <strong>Buyer: </strong><%= @order.user.email%></p>

<p>
  <strong>Price:</strong>
  $<%= @order.listing.price %>
</p>

<p>
  <strong>Category:</strong>
  <%= @order.listing.category %>
</p>

<p>
  <strong>Console compatibility:</strong>
  <%= @order.listing.console_compatibility %>
</p>

<p>
  <strong>Functional condition:</strong>
  <%= @order.listing.functional_condition %> / 3 :
  <% if @order.listing.cosmetic_condition == 1 %>
  <%= 'Not functional; for parts or repair' %>
  <% elsif @order.listing.cosmetic_condition == 2 %>
  <%= 'Works the majority of the time with some bugs/errors' %>
  <% elsif @order.listing.cosmetic_condition == 3 %>
  <%= 'Works flawlessly'%>
  <% end %>
</p>

<p>
  <strong>Cosmetic condition:</strong>
  <%= @order.listing.cosmetic_condition %> / 3 :
  <% if @order.listing.cosmetic_condition == 1 %>
  <%= 'Heavy damage / scratching' %>
  <% elsif @order.listing.cosmetic_condition == 2 %>
  <%= 'Some visible damage / scratching' %>
  <% elsif @order.listing.cosmetic_condition == 3 %>
  <%= 'No scratches or damage'%>
  <% end %>

</p>

<p>
    <strong>Item Location: </strong>
    <%= @order.listing.user.suburb %>,
    <%= @order.listing.user.state%>
</p>

<p>
  <strong>Description:</strong>
  <%= @order.listing.description %>
</p>

<%= link_to 'Back', orders_path, class: 'btn btn-primary' %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Game Away</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>
        
        <% if user_signed_in? %>
          <li class="nav-item">
              <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link'%>
          </li>
          <li class="nav-item">
              <%= link_to 'My Account', edit_user_registration_path, class: 'nav-link'%>
          </li>
          <li class="nav-item">
              <%= link_to 'My Orders', orders_path, class: 'nav-link'%>
          </li>
          <li class="nav-item">
              <%= link_to 'New Listing', new_listing_path, class: 'nav-link'%>
          </li>
        <% else %>
          <li class="nav-item">
              <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>